name: Release Please

on:
  push:
    branches: [main]

jobs:

  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Executar Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: java
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # token com permissões elevadas para criar PRs e tags
          # o GITHUB_TOKEN padrão não tem permissão suficiente para esta operação